### ISSUE TITLE
Awt support

### ISSUE THREAD

**Issue by lytico** [lytico/ikvm#1]
see: https://github.com/ikvmnet/ikvm/issues/144

and example for enabling support:

https://github.com/ikvmnet/ikvm/pull/483

and there eg. the clang proj:
https://github.com/ikvmnet/ikvm/pull/483/files#diff-aacbc68c8761771400c4bf7adcad2525d4ebdfb0fb92c82940a9f9e932504bdc

jdk awt build can be found here:

https://github.com/ikvmnet/jdk8u/blob/e58c8a60e38ef345be29ff8277dcac903044797a/jdk/make/lib/Awt2dLibraries.gmk

**Comment by GeorgeS2019** [comment]
@lytico 
https://github.com/ikvmnet/ikvm/issues/381#issuecomment-2065922797

**Comment by lytico** [comment]
@GeorgeS2019 thanks for the hint!!!

**Comment by GeorgeS2019** [comment]
https://github.com/ikvmnet/ikvm/pull/528
